// Builds the downloadable analysis report (standalone HTML) and handles
// chart export to PNG. No dependencies — pure DOM APIs.

export type Stat = { label: string; value: string };

const esc = (s: string) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Triggers a browser download for a Blob. */
export function downloadBlob(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/** Serializes a Table back to CSV text. */
export function tableToCsv(headers: string[], rows: string[][]): string {
  const cell = (v: string) =>
    /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
  return [headers, ...rows].map((r) => r.map(cell).join(",")).join("\r\n");
}

export type ReportOptions = {
  title: string;
  kind: string;
  fileName: string;
  portfolioUrl: string;
  stats: Stat[];
  /** Serialized <svg> markup for chart visuals. */
  visualSvg?: string;
  /** Pre-rendered HTML for table visuals. */
  visualHtml?: string;
  headers: string[];
  rows: string[][];
};

/** Assembles a styled, self-contained HTML report document. */
export function buildHtmlReport(o: ReportOptions): string {
  const date = new Date().toLocaleString();
  const stats = o.stats
    .map(
      (s) =>
        `<div class="stat"><div class="sl">${esc(s.label)}</div><div class="sv">${esc(s.value)}</div></div>`,
    )
    .join("");
  const preview = o.rows.slice(0, 60);
  const thead = `<tr>${o.headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr>`;
  const tbody = preview
    .map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`)
    .join("");
  const visual = o.visualSvg
    ? `<div class="viz">${o.visualSvg}</div>`
    : o.visualHtml
      ? `<div class="viz">${o.visualHtml}</div>`
      : "";

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${esc(o.title)} — Report</title>
<style>
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;background:#070a12;color:#e8edf7;
font-family:ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif;line-height:1.5}
.wrap{max-width:1040px;margin:0 auto;padding:48px 24px}
.kick{font-family:ui-monospace,monospace;font-size:11px;letter-spacing:.22em;
text-transform:uppercase;color:#8a93a6}
h1{font-size:30px;margin:8px 0 6px;letter-spacing:-.02em}
.grad{background:linear-gradient(110deg,#4c8dff,#9a6bff,#3de0c2);
-webkit-background-clip:text;background-clip:text;color:transparent}
.meta{font-size:12px;color:#8a93a6}
.head{border-bottom:1px solid rgba(255,255,255,.1);padding-bottom:22px;margin-bottom:8px}
h2{font-size:13px;text-transform:uppercase;letter-spacing:.14em;
color:#8a93a6;margin:34px 0 12px;font-weight:600}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}
.stat{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);
border-radius:12px;padding:14px 16px}
.sl{font-size:11px;color:#8a93a6;text-transform:uppercase;letter-spacing:.07em}
.sv{font-size:19px;font-weight:600;margin-top:5px}
.viz{background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.08);
border-radius:14px;padding:18px;overflow:auto}
.viz svg{width:100%;height:auto;display:block}
.tablewrap{overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:12px}
table{border-collapse:collapse;width:100%;font-size:12px}
th,td{text-align:left;padding:8px 11px;border-bottom:1px solid rgba(255,255,255,.06);
white-space:nowrap}
th{color:#cdd5e6;font-weight:600;background:rgba(255,255,255,.03)}
td{color:#9aa3b4}
.foot{margin-top:40px;border-top:1px solid rgba(255,255,255,.1);
padding-top:18px;font-size:12px;color:#5a6072}
.foot a{color:#4c8dff;text-decoration:none}
</style></head><body><div class="wrap">
<div class="head">
<div class="kick">generated data report</div>
<h1>${esc(o.title)} <span class="grad">Report</span></h1>
<div class="meta">Source file: ${esc(o.fileName)} &nbsp;·&nbsp; Generated ${esc(date)}</div>
</div>
<h2>Summary</h2>
<div class="stats">${stats}</div>
${visual ? `<h2>Visualization</h2>${visual}` : ""}
<h2>Data — first ${preview.length} of ${o.rows.length} rows</h2>
<div class="tablewrap"><table><thead>${thead}</thead><tbody>${tbody}</tbody></table></div>
<div class="foot">Generated by the interactive ${esc(o.kind)} tool on the portfolio of
<strong>Anuj Kumar</strong>, Data Visualization Engineer.
&nbsp;<a href="${esc(o.portfolioUrl)}">${esc(o.portfolioUrl)}</a></div>
</div></body></html>`;
}

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("The chart could not be rasterized."));
    img.src = url;
  });
}

/** Rasterizes an on-page SVG chart to a PNG Blob. */
export async function svgToPng(
  svg: SVGSVGElement,
  scale = 2,
  bg = "#0b1018",
): Promise<Blob> {
  const clone = svg.cloneNode(true) as SVGSVGElement;
  const vb = svg.viewBox.baseVal;
  const w = vb && vb.width ? vb.width : svg.clientWidth || 920;
  const h = vb && vb.height ? vb.height : svg.clientHeight || 540;
  clone.setAttribute("width", String(w));
  clone.setAttribute("height", String(h));
  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  const markup = new XMLSerializer().serializeToString(clone);
  const url = URL.createObjectURL(
    new Blob([markup], { type: "image/svg+xml;charset=utf-8" }),
  );
  try {
    const img = await loadImage(url);
    const canvas = document.createElement("canvas");
    canvas.width = Math.round(w * scale);
    canvas.height = Math.round(h * scale);
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas is unavailable in this browser.");
    ctx.fillStyle = bg;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    return await new Promise<Blob>((resolve, reject) =>
      canvas.toBlob(
        (b) => (b ? resolve(b) : reject(new Error("PNG encoding failed."))),
        "image/png",
      ),
    );
  } finally {
    URL.revokeObjectURL(url);
  }
}
